sdk.dir=C\:/Users/804/AppData/Local/Android/Sdk
daengs.kakaoNativeAppKey=ee08804f17e4cf7920505b9be2ccf8f1
daengs.apiBaseUrl=http://daengback.weareithero.cloud/
daengs.screenUrl=http://daengback.weareithero.cloud/screen
daengs.naverMapClientId=zp5oys999u
daengs.naverMapStyleId=74b72b63-e6a4-4435-b954-9d40da784f79
daengs.uploadKeyStore=keystore/upload.jks
daengs.uploadKeyAlias=daengs-upload
daengs.uploadKeyPassword=0dhBJzerB0wTz3B8g2JpS591b6UWXVPP